[theme]

# Primary accent for interactive elements
primaryColor = '#ccb3ff'

# Background color for the main content area
backgroundColor = '#000000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#4d4d4d'

# Color used for almost all text
textColor = '#ffffff'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
#font = "sans serif"